export default [
  {
    id : 1,
    year : "04/2020 > 07/2020", 
    job : "Stage Web Developer Full Stack", 
    society : "Banlieues Asbl",
    city : "Brussels",
    workDescription : 'Banlieues helps organizations in the voluntary sector to enter the world of ICT and offer technological products and services tailored to their needs. I worked on a project called Cformatplus. I did a form in which the users can register for a video-conference on the date that suits them with a date-picker and a captcha. I created a view in which displays a list of registered users with buttons in which an employee can send emails to the users. I did the whole page, i coded and set up the mailing service as well. l created a page in which the employees will be able to write an email that must be sent to registered users using a summernoteJs library. I did bug fixing. Analysis using different UML diagrams Unit and integration Tests. SQL queries development. I used PHP, JavaScript as programming languages, PHPMyAdmin as SGBD, codeIgniter as framework, jQuery, datePickerJs, summernoteJs.',
    },
  {
    id : 2,
    year : "2014 > 2018", 
    job : "Sales Coordinator", 
    society : "Vee-Pee",
    city : "Brussels",
    workDescription : 'Leader in online flash sales in Belgium. Shooting, commercial descriptions and online publication of the various products.',
  },
  {
    id : 3,
    year : "2012 > 2013", 
    job : "Store Manager", 
    society : "B52 Stores",
    city : "Brussels",
    workDescription : "Women's and men's clothing shop. Entire store management.",
  },
  {
    id : 4,
    year: "2010 > 2012", 
    job : "Saleswomen", 
    society : "Aragon communications",
    city : "Brussels",
    workDescription : "Communication agency. Application of commercial techniques and new prospects searching.",
  },
  {
    id : 5,
    year: "2007 > 2009", 
    job : "Saleswomen", 
    society : "B52 Stores",
    city : "Brussels",
    workDescription : "Women's and men's clothes and shoe store product shelving, maintenance, storage management, cashier.",
  }, 
]